Introduction to NumPy

In [2]:
import numpy as np

Basic Array Creation

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

From Python Lists

In [6]:
#Convert a python list to a Numpy array
a = np.array([1,2,3,5,7,12])

Accessing and modifying elements

In [7]:
#Access elements using zero-based indexing
a[2]
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

Range based arrays

In [8]:
#create arrays with sequential values
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi-Dimensional arrays

In [11]:
#create 2D arrays
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([[1,2,3], [4,5,6], [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Accessing elements in 2D Arrays

In [13]:
n[0,1] #access element at row 0, column 1(value :2)
n[0,1] = 20 # Change this element to 20

Accessing Rows and columns

In [16]:
n[0] #Access the first row
n[2] = [1,1,1] #Replace the last row with ones
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [17]:
n[:,1] #Access the second column (all rows, column 1)
n[:,2] = [0, 1, 2] #replace the last column
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

Randomly generated arrays

In [19]:
#Uniform distribution

np.random.random((5,2))

array([[0.05704089, 0.09938653],
       [0.85248197, 0.30482997],
       [0.42660777, 0.27634467],
       [0.4843464 , 0.96589168],
       [0.49491045, 0.60684447]])

In [20]:
#Setting random seed
#Make random generation reproducible
np.random.seed(2)
np.random.random((5,2)) #will produce the same "random" values every time

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

Normal distribution

In [21]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

Random integers

In [23]:
#Random integers between 0 and 99
np.random.randint(0,100,(5,2))

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]])

Element-wise operations

In [25]:
#Numpy arrays support arithmetic operations that apply to each element
a = np.arange(5)

a + 1
a * 2
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [26]:
#operations can be chained
a * 2 + 10 #[10, 12, 14, 16, 18]

array([10, 12, 14, 16, 18])

In [27]:
(a * 2 + 10) ** 2

array([100, 144, 196, 256, 324])

Operations Between arrays

In [29]:
a = np.arange(5)
b = np.array([10,10,10,10,10])

In [31]:
a + b

array([10, 11, 12, 13, 14])

In [32]:
a * b

array([ 0, 10, 20, 30, 40])

Comparison operations

In [33]:
a >= 2

array([False, False,  True,  True,  True])

In [34]:
a > b

array([False, False, False, False, False])

In [35]:
#Filter arrays using boolean masks
a[a > b] #Returns elements of a where a > b is true

array([], dtype=int64)

Summarizing operations

In [40]:
#Reduce arrays to single values
np.min(a)

np.int64(0)

In [39]:
np.max(a)

np.int64(4)

In [41]:
np.sum(a)

np.int64(10)

In [42]:
np.mean(a)

np.float64(2.0)

In [43]:
np.std(a) #standard deviation

np.float64(1.4142135623730951)